services:
  app:
    image: kannikk/express-app:latest
    container_name: express-app
    ports:
      - "3000:3000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_API_VERSION: "1.54"
    command: --interval 60 express-app
